version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "pgsqlpass"
    ports:
      - "5432:5432"